### ISSUE TITLE
What is the role of “ $scope: any ” ?

### ISSUE THREAD

**Issue by yuzhongwusan** [yosshitaku067/ionic-webpack-es6-starter#1]
module.exports = ($scope: any, $state: any, ImagePath: any, GreetingService: any) => {}

What is the role of “ $scope: any ” ?

**Comment by yosshitaku067** [comment]
Thanks for seeing my project.
It's defining variable type as any, because this project uses flowtype. If you want to define appropriate type, you have to write or install declaration file.

**Comment by yuzhongwusan** [comment]
Thanks
