### ISSUE TITLE
How to automate compilation？

### ISSUE THREAD

**Issue by yuzhongwusan** [yosshitaku067/ionic-webpack-es6-starter#2]
hello sir：
  Thank you for your reply to the last question, I encountered the following question。

npm run start

When I modify a "js" or "html" file, it is not automatically compiled and reflected in the current http: // localhost: 8100 / # / first

I used notePad ++

**Comment by yosshitaku067** [comment]
I added setting for watching code modify.
Please pull latest version then
```bash
npm install
npm run start
```

First, open browser automatically, then start webpack build.
Just a little while, please refresh browser.
start app, and watching code.

**Comment by yuzhongwusan** [comment]
Hello,sir:
**I executed the command "npm install" found the following error：**

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":
"} (current: {"os":"win32","arch":"x64"})
npm WARN uglifyjs-webpack-plugin@0.1.5 requires a peer of uglify-js@^2.7.5 but none was installed.
npm WARN ionic-webpack-es6-starter@1.1.1 No repository field.
npm WARN ionic-webpack-es6-starter@1.1.1 No license field.`



**Automatic compilation function is achieved, but why do I need to refresh the browser every time I can see the results, rather than automatically refresh the browser?**

**Comment by yosshitaku067** [comment]
Hi!
Maybe, your OS is Windows, isn't it?
I had tried Mac OS.
In my environment, I confirm that the update result is automatically reflected after the first refresh.

Please wait a moment as I will check on Windows environment from now.

**Comment by yosshitaku067** [comment]
Hi!

Sorry I made you wait. I confirmed that it will be updated automatically in Windows environment. I confirmed it using the Chrome browser. 

```bash
npm install
npm run start
```
If it does not work please clone it again.

**Tested environment**

```bash
$ ionic info

global packages:
 
    @ionic/cli-utils : 1.4.0
    Gulp CLI         : not installed globally
    Ionic CLI        : 3.4.0
 
local packages:
 

    @ionic/cli-plugin-gulp   : 1.0.1
    @ionic/cli-plugin-ionic1 : 2.0.0
    Ionic Framework          : ionic1 1.3.2
 
System:
 
    Node       : v7.2.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.0.3
```

**Comment by yuzhongwusan** [comment]
Hi!
I am now on the outside, the company's computer is win7, the browser is Google
I use "download zip" to download all the files.
I will try again, the news will tell you in time.

**Comment by yuzhongwusan** [comment]
```
PS E:\webpack_2\ionic_es62> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN ionic-webpack-es6-starter@1.1.1 No repository field.
npm WARN ionic-webpack-es6-starter@1.1.1 No license field.
```
`PS E:\webpack_2\ionic_es62> npm install fsevents
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "fsevents"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     E:\webpack_2\ionic_es62\npm-debug.log`

**Comment by yuzhongwusan** [comment]
**npm install**
```
npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update t
o graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end pr
ojects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Curre
ntly there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

【Installed other plugins are successful】
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN ionic-webpack-es6-starter@1.1.1 No repository field.
npm WARN ionic-webpack-es6-starter@1.1.1 No license field.
```

**Comment by yosshitaku067** [comment]
Hi!
Thank you to try.
Tokyo is very hot and humid!

When building with windows, warning about fsevents comes out, but you can ignore it.
fsevents seems only to be needed when building on OS X So.

Can you update the version of Ionic CLI?
Execute the following command and check whether the latest build environment is prepared.

```bash
$ npm install -g ionic@latest
$ ionic info
```

Then, if it does not work, delete the 「node_modules」 folder once, clear the cache of npm, and try npm install.

**Comment by yuzhongwusan** [comment]
**Operation is as follows**

```
1. npm install -g ionic@latest
2. ionic info
```


global packages:

    @ionic/cli-utils : 1.4.0
    Gulp CLI         : CLI version 3.9.1 Local version 3.9.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/cli-plugin-gulp   : 1.0.1
    @ionic/cli-plugin-ionic1 : 2.0.0
    Ionic Framework          : ionic1 1.3.2

System:

    Node       : v8.1.3
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3


`3.npm run start`

.......
Webpack is watching the files…

[ERROR] Gulpfile not found: .\gulpfile.js
        You can set the gulpFile attribute in ionic.config.json for custom Gulpfile locations, otherwise the default
        Ionic Gulpfile can be downloaded from https://github.com/ionic-team/ionic-app-base/blob/master/gulpfile.js

        Or, if you no longer use gulp, you can remove the CLI Gulp Plugin:

        npm uninstall --save-dev --save-exact @ionic/cli-plugin-gulp@latest

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-webpack-es6-starter@1.1.1 watch:serve: `ionic serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-webpack-es6-starter@1.1.1 watch:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ycdeng\AppData\Roaming\npm-cache\_logs\2017-07-07T13_26_34_347Z-debug.log
ERROR: "watch:serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-webpack-es6-starter@1.1.1 start: `npm-run-all --parallel clean watch:serve watch:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-webpack-es6-starter@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ycdeng\AppData\Roaming\npm-cache\_logs\2017-07-07T13_26_34_655Z-debug.log
PS E:\webpack\7.6>

`4. delete node_module`
`5. npm install`
'6.npm run start'

> ionic-webpack-es6-starter@1.1.1 watch:build E:\webpack\7.6
> webpack --watch


┌────────────────────────────────────────────────────────
──┐
│                   npm update check failed                   │
│             Try running with sudo or get access             │
│            to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\ycdeng\.config │
└────────────────────────────────────────────────────────
──┘
loader option has been deprecated - replace with "use"

Webpack is watching the files…

[ERROR] Gulpfile not found: .\gulpfile.js
        You can set the gulpFile attribute in ionic.config.json for custom Gulpfile locations, otherwise the defa
        Ionic Gulpfile can be downloaded from https://github.com/ionic-team/ionic-app-base/blob/master/gulpfile.j

        Or, if you no longer use gulp, you can remove the CLI Gulp Plugin:

        npm uninstall --save-dev --save-exact @ionic/cli-plugin-gulp@latest

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-webpack-es6-starter@1.1.1 watch:serve: `ionic serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-webpack-es6-starter@1.1.1 watch:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ycdeng\AppData\Roaming\npm-cache\_logs\2017-07-07T13_31_36_283Z-debug.log
ERROR: "watch:serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-webpack-es6-starter@1.1.1 start: `npm-run-all --parallel clean watch:serve watch:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-webpack-es6-starter@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ycdeng\AppData\Roaming\npm-cache\_logs\2017-07-07T13_31_36_615Z-debug.log
PS E:\webpack\7.6>

**Comment by yuzhongwusan** [comment]
Successful, thank you for your help.
According to the following error message:
```
[ERROR] Gulpfile not found:. \ Gulpfile.js
You can set the gulpFile attribute in ionic.config.json for custom Gulpfile locations, otherwise the default
Ionic Gulpfile can be downloaded from https://github.com/ionic-team/ionic-app-base/blob/master/gulpfile.js
```
# Processing and results
1. Reinstall gulp
2. the current operation of your project gulp [because there are gulpfile.js]
    Run failed, suggesting that some gulp plugins are not installed
3. Follow the prompts to install some plugins [gulpfile.js files that are required or other gulp plugins]
4. remove gulpfile.js in sass any and plugin [always download failed]
5.npm run start
6. Modify fisrt.html and first.js are able to achieve the browser automatically refresh
